const ACHIEVEMENT_KEYS = Object.freeze([
  'blitzkrieg',
  'chrono',
  'cleanHands',
  'duel',
  'duo',
  'fainthearted',
  'first',
  'freedom',
  'hermit',
  'impertinence',
  'keepMoving',
  'last',
  'mystique',
  'nomad',
  'quickAndFurious',
  'scanty',
  'statue',
  'tight',
  'timeFlies',
  'untouchable',
  'versatile',
  'zombie',
]);

const CHALLENGE_KEYS = Object.freeze([
  'barbaric',
  'battleRoyal',
  'blitzkrieg',
  'chrono',
  'cleanHands',
  'contamination',
  'contractKiller',
  'cruel',
  'duel',
  'elementaryMyDear',
  'elitist',
  'evasive',
  'exhuberant',
  'fainthearted',
  'focus',
  'foresighted',
  'gangster',
  'hermit',
  'impertinence',
  'keepMoving',
  'lowLevelsFirst',
  'loyalFriend',
  'maniac',
  'mystique',
  'noRush',
  'nomad',
  'quickAndFurious',
  'reprieve',
  'rootedToTheSpot',
  'scanty',
  'scapegoat',
  'selfSacrifice',
  'sharing',
  'sightseeing',
  'static',
  'statue',
  'survivor',
  'tight',
  'timeFlies',
  'toEachHisPwn',
  'twoForThePriceOfOne',
  'uncurable',
  'unpredictable',
  'untouchable',
  'unwillingVolunteer',
  'versatile',
  'zombie',
]);

const CATEGORIES = Object.freeze({
  achievements: ACHIEVEMENT_KEYS,
  challenges: CHALLENGE_KEYS,
});

module.exports = {
  ACHIEVEMENT_KEYS,
  CHALLENGE_KEYS,
  CATEGORIES
};