const { ICON_BASE } = require('./shared');

const BOSSE_LISTE = [
  // Level 1 - 50 Dungeons
  { id: 'belladonna',
    name: {
      de: 'Belladonna', en: 'Belladonna', fr: 'Belladone', es: 'Belladona',
    },
    imageUrl: `${ICON_BASE}/boss-icons/belladonna.png`,
    defaultLevel: 12,
    region: 'albuera',
    family: 'albuera',
    characteristics: {
      vitality: 120,
      actionPoints: 7,
      movementPoints: 3
    },
    resistances: {
      neutral: 0,
      earth: 0,
      fire: 0,
      water: 0,
      air: 0,
    }
  },
  { id: 'famished_sunflower',
    name: {
      de: 'Ausgehungertes Sonnenblümchen',
      en: 'Famished Sunflower',
      fr: 'Tournesol Affamé',
      es: 'Girasol Hambriento',
    },
    imageUrl: `${ICON_BASE}/boss-icons/famished_sunflower.png`,
    defaultLevel: 35,
    resistances: {
      neutral: 25,
      earth: 25,
      fire: 15,
      water: -10,
      air: -15
    } },
  { id: 'spongemob',
    name: {
      de: 'Spongemob Schwammtopf',
      en: 'Sponge Mob',
      fr: 'Mob l\'Éponge',
      es: 'Mob Lasponja'
    },
    imageUrl: `${ICON_BASE}/boss-icons/spongemob.png`,
    defaultLevel: 40,
    resistances: {
      neutral: 22,
      earth: 14,
      fire: -5,
      water: 14,
      air: -5,
    } },
  { id: 'golden_scarabugly',
    name: {
      de: 'Goldenes Scarabiest',
      en: 'Golden Scarabugly',
      fr: 'Scarabosse Doré',
      es: 'Escarajefe Dorado',
    },
    imageUrl: `${ICON_BASE}/boss-icons/golden_scarabugly.png`,
    defaultLevel: 40,
    resistances: {
      neutral: 24,
      earth: 24,
      fire: 24,
      water: 24,
      air: 24,
    } },
  { id: 'batofu',
    name: {
      de: 'Batofu',
      en: 'Batofu',
      fr: 'Batofu',
      es: 'Batofu',
    }, imageUrl: `${ICON_BASE}/boss-icons/batofu.png`,
    defaultLevel: 40,
    resistances: {
      neutral: 14,
      earth: 9,
      fire: -25,
      water: -15,
      air: 37,
    } },
  { id: 'boostache',
    name: {
      de: 'Bartaboo',
      en: 'Boostache',
      fr: 'Boostache',
      es: 'Boostacho',
    },
    imageUrl: `${ICON_BASE}/boss-icons/boostache.png`,
    defaultLevel: 40,
    resistances: {
      neutral: 55,
      earth: 0,
      fire: 0,
      water: 15,
      air: 85,
    } },
  { id: 'ronin_chafer', name: 'Ronin Chafer', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3238.w200h.png', defaultLevel: 40 },
  { id: 'kingfresssack', name: 'Königlicher Fresssack', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/147.w200h.png', defaultLevel: 50 },
  { id: 'bworkette', name: 'Bworkette', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/792.w200h.png', defaultLevel: 50 },
  { id: 'schattenschmiede', name: 'Schatztruhe der Schattenschmiede', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/252.w200h.png', defaultLevel: 50 },
  { id: 'shin_larve', name: 'Shin Larve', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/457.w200h.png', defaultLevel: 50 },
  { id: 'korallator', name: 'Mächtiger Korallator', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1027.w200h.png', defaultLevel: 50 },
  { id: 'kwackatau', name: 'Kwackatau', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/2995.w200h.png', defaultLevel: 50 },
  // Level 51 - 100 Dungeons
  { id: 'wa_wabbit', name: 'Wa Wabbit', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/180.w200h.png', defaultLevel: 60 },
  { id: 'ahde', name: 'Kanniball Ahde', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/2960.w200h.png', defaultLevel: 60 },
  { id: 'apfel_blob', name: 'Königlicher Apfel Blob', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1187.w200h.png', defaultLevel: 60 },
  { id: 'indigo_blob', name: 'Königlicher Indigo Blob', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1186.w200h.png', defaultLevel: 60 },
  { id: 'kirsch_blob', name: 'Königlicher Kirsch Blob', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1185.w200h.png', defaultLevel: 60 },
  { id: 'kokos_blob', name: 'Königlicher Kokos Blob', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1184.w200h.png', defaultLevel: 60 },
  { id: 'minzgelee', name: 'Königliches Minzgelee', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/85.w200h.png', defaultLevel: 60 },
  { id: 'erdbeergelee', name: 'Königliches Erdbeergelee', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/86.w200h.png', defaultLevel: 60 },
  { id: 'zitronengelee', name: 'Königliches Zitronengelee', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/430.w200h.png', defaultLevel: 60 },
  { id: 'blaubeergelee', name: 'Königliches Blaubeergelee', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/58.w200h.png', defaultLevel: 60 },
  { id: 'nelwynn', name: 'Nelwynn', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3100.w200h.png', defaultLevel: 70 },
  { id: 'gurrlo', name: 'Gurrlo, der Fürchterliche', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1051.w200h.png', defaultLevel: 70 },
  { id: 'mega_krachler', name: 'Legendärer Mega Krachler', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/669.w200h.png', defaultLevel: 70 },
  { id: 'wa_wobot', name: 'Wa Wobot', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3460.w200h.png', defaultLevel: 80 },
  { id: 'urasta', name: 'Ur-Astaknyde', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/173.w200h.png', defaultLevel: 90 },
  { id: 'oberstnimb', name: 'Oberstnimb Selim Quarz', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3585.w200h.png', defaultLevel: 90 },
  { id: 'schweinedrachen', name: 'Schweinedrachen', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/113.w200h.png', efaultLevel: 100 },
  { id: 'kuhloss', name: 'Kuhloss', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/670.w200h.png', defaultLevel: 100 },
  { id: 'moon', name: 'Moon', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/226.w200h.png', defaultLevel: 400 },
  { id: 'muwulf', name: 'MuWulf', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/232.w200h.png', defaultLevel: 100 },
  // Level 101 - 150 Dungeons
  { id: 'gross_shilf', name: 'Groß-Shilf', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1071.w200h.png', defaultLevel: 440 },
  { id: 'meister_rab', name: 'Meister Rab', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/289.w200h.png', defaultLevel: 110 },
  { id: 'weisse_ratte', name: 'Weiße Ratte', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/940.w200h.png', defaultLevel: 110 },
  { id: 'schwarze_ratte', name: 'Schwarze Ratte', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/939.w200h.png', defaultLevel: 110 },
  { id: 'kingmultiblob', name: 'Königlicher Multiblob', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1188.w200h.png', defaultLevel: 120 },
  { id: 'minotoror', name: 'Minotoror', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/121.w200h.png', defaultLevel: 120 },
  { id: 'kingfressmut', name: 'Königliches Fressmut', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/2854.w200h.png', defaultLevel: 120 },
  { id: 'kingtofu', name: 'Königlicher Tofu', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/382.w200h.png', defaultLevel: 120 },
  { id: 'crocabulia', name: 'Crocabulia', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/854.w200h.png', defaultLevel: 120 },
  { id: 'skeunk', name: 'Skeunk', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/780.w200h.png', defaultLevel: 120 },
  { id: 'krakillian', name: 'Krakillian Wächter', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3794.w200h.png', defaultLevel: 130 },
  { id: 'kanigroula', name: 'Kanigroula', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3774.w200h.png', defaultLevel: 140 },
  { id: 'weicheich', name: 'Weich Eich', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/257.w200h.png', defaultLevel: 140 },
  { id: 'tynril_best', name: 'Bestürzter Tynril', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1072.w200h.png', defaultLevel: 140 },
  { id: 'tynril_perf', name: 'Perfider Tynril', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1086.w200h.png', defaultLevel: 140 },
  { id: 'tynril_verb', name: 'Verblüffter Tynril', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1087.w200h.png', defaultLevel: 140 },
  { id: 'tynril_verd', name: 'Verdutzter Tynril', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1085.w200h.png', defaultLevel: 140 },
  { id: 'ping', name: 'King Ping', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/2848.w200h.png', defaultLevel: 162 },
  { id: 'mina', name: 'Hell Mina', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/4318.w200h.png', defaultLevel: 140 },
  { id: 'ben', name: 'Ben der Ripat', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/2877.w200h.png', defaultLevel: 150 },
  { id: 'sphincter', name: 'Sphincter Cell', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/943.w200h.png', defaultLevel: 150 },
  // Level 151 - 190 Dungeons
  { id: 'kimbo', name: 'Kimbo', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1045.w200h.png', defaultLevel: 160 },
  { id: 'minotot', name: 'Minotot', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/827.w200h.png', defaultLevel: 160 },
  { id: 'obsi', name: 'Obsidianter', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/2924.w200h.png', defaultLevel: 160 },
  { id: 'zombrute', name: 'Zombrutalist', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3772.w200h.png', defaultLevel: 160 },
  { id: 'tengu', name: 'Tengu Eisfux', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/2967.w200h.png', defaultLevel: 170 },
  { id: 'fuji', name: 'Fuji Eisfux', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3234.w200h.png', defaultLevel: 190 },
  { id: 'nagate', name: 'Nagate', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3944.w200h.png', defaultLevel: 170 },
  { id: 'skai', name: 'König Skai', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3671.w200h.png', defaultLevel: 170 },
  { id: 'korri', name: 'Korriander', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/2968.w200h.png', defaultLevel: 180 },
  { id: 'krakamor', name: 'Riesenkrakamor', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/423.w200h.png', defaultLevel: 180 },
  { id: 'bworker', name: 'Bworker', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/478.w200h.png', defaultLevel: 180 },
  { id: 'stinker', name: 'Stinkeling', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1159.w200h.png', defaultLevel: 180 },
  { id: 'tanuki', name: 'Tanukouï San', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3990.w200h.png', defaultLevel: 180 },
  { id: 'daxolossus', name: 'Daxolossus', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/2986.w200h.png', defaultLevel: 190 },
  { id: 'professor', name: 'Professor Xa', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/2992.w200h.png', defaultLevel: 190 },
  { id: 'fuxoroshi', name: 'Fuxoroshi', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3954.w200h.png', defaultLevel: 190 },
  { id: 'grollum', name: 'Grollum', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/2942.w200h.png', defaultLevel: 190 },
  { id: 'barbaer', name: 'Himmlischer Barbär', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/4347.w200h.png', defaultLevel: 200 },
  { id: 'shihan', name: 'Shihan', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3932.w200h.png', defaultLevel: 200 },
  { id: 'hanshi', name: 'Hanshi', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3924.w200h.png', defaultLevel: 200 },
  // Level 191 - 200 Dungeons
  { id: 'frizz', name: 'Missiz Frizz', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3391.w200h.png', defaultLevel: 220 },
  { id: 'sylargh', name: 'Sylargh', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3409.w200h.png', defaultLevel: 220 },
  { id: 'klimm', name: 'R.Klimm', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3384.w200h.png', defaultLevel: 220 },
  { id: 'nileza', name: 'Nileza', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3397.w200h.png', defaultLevel: 220 },
  { id: 'primzahl', name: 'Graf Primzahl', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3416.w200h.png', defaultLevel: 220 },
  { id: 'damadrya', name: 'Damadrya', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3972.w200h.png', defaultLevel: 200 },
  { id: 'katamashii', name: 'Katamashii', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/4411.w200h.png', defaultLevel: 220 },
  // Saisonale Bosse
  { id: 'mucane', name: 'Mucane', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3652.w200h.png', defaultLevel: 150 },
  { id: 'ulkhan', name: 'Ul-Khan', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3647.w200h.png', defaultLevel: 200 },
  { id: 'grasmera_schlaf', name: 'Schlafwandelnder Grasmera', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3298.w200h.png', defaultLevel: 100 },
  { id: 'grozilla_schlaf', name: 'Schlafwandelnder Grozilla', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3295.w200h.png', defaultLevel: 100 },
  { id: 'grasmera_ersch', name: 'Erschöpfter Grasmera', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3297.w200h.png', defaultLevel: 200 },
  { id: 'grozilla_ersch', name: 'Erschöpfter Grozilla', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3294.w200h.png', defaultLevel: 200 },
  { id: 'grasmera_mued', name: 'Müder Grasmera', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3296.w200h.png', defaultLevel: 300 },
  { id: 'grozilla_mued', name: 'Müder Grozilla', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3293.w200h.png', defaultLevel: 300 },
  { id: 'grasmera', name: 'Grasmera', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3143.w200h.png', defaultLevel: 400 },
  { id: 'grozilla', name: 'Grozilla', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3142.w200h.png', defaultLevel: 400 },
  { id: 'sauger', name: 'Mark Sauger', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3650.w200h.png', defaultLevel: 60 },
  { id: 'hoellofeen', name: 'Höll OFeen', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3306.w200h.png', defaultLevel: 100 },
  { id: 'deleghul', name: 'Personal Deleghul', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/3557.w200h.png', defaultLevel: 220 },
  { id: 'pisack', name: 'Pi_Sack', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1179.w200h.png', defaultLevel: 50 },
  { id: 'weissnachtsmann', name: 'Weißnachtsmann', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/872.w200h.png', defaultLevel: 110 },
  { id: 'rubraecher', name: 'Rubrächer, der Knechter', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/1194.w200h.png', defaultLevel: 180 },
  { id: 'minotoball', name: 'Weißnachts-Minotoball', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/2819.w200h.png', defaultLevel: 1000 },
  { id: 'vlad', name: 'Dark Vlad', imageUrl: 'https://static.ankama.com/dofus-touch/www/game/monsters/200/4631.w200h.png', defaultLevel: 300 },
];

module.exports = { BOSSE_LISTE };