const DUNGEON_LISTE = [
  // Stufe 1 - 50
  { dungeonname: 'Belladonnas Schloss', bossname: 'Belladonna', level: 12 },
  { dungeonname: 'Felder Dungeon', bossname: 'Ausgehungertes Sonnenblümchen', level: 30 },
  { dungeonname: 'Versandeter Dungeon', bossname: 'Spongemob Schwammtopf', level: 40 },
  { dungeonname: 'Scarablatt Dungeon', bossname: 'Goldenes Scarabiest', level: 40 },
  { dungeonname: 'Tofu Dungeon', bossname: 'Batofu', level: 40 },
  { dungeonname: 'Geisterhaus', bossname: 'Bartaboo', level: 40 },
  { dungeonname: 'Dungeon der Skelette', bossname: 'Ronin Chafer', level: 40 },
  { dungeonname: 'Fresssack Dungeon', bossname: 'Königlicher Fresssack', level: 50 },
  { dungeonname: 'Bwork Dungeon', bossname: 'Bworkette', level: 50 },
  { dungeonname: 'Dungeon der Schattenschmiede', bossname: 'Schatztruhe der Schattenschmiede', level: 50 },
  { dungeonname: 'Larven Dungeon', bossname: 'Shin Larve', level: 50 },
  { dungeonname: 'Aggrotte', bossname: 'Mächtiger Korallator', level: 50 },
  { dungeonname: 'Nest des Kwackataus', bossname: 'Kwackatau', level: 50 },
  // Stufe 51 - 100
  { dungeonname: 'Schloss des Wa Wabbits', bossname: 'Wa Wabbit', level: 60 },
  { dungeonname: 'Kanniball Dungeon', bossname: 'Kanniball Ahde', level: 60 },
  { dungeonname: 'Blob Dungeon',
    bosses: [
      { bossname: 'Königlicher Apfel Blob', level: 60 },
      { bossname: 'Königlicher Indigo Blob', level: 60 },
      { bossname: 'Königlicher Kirsch Blob', level: 60 },
      { bossname: 'Königlicher Kokos Blob', level: 60 },
    ],
  },
  { dungeonname: 'Königliche Gelee Dimension',
    bosses: [
      { bossname: 'Königliches Minzgelee', level: 60 },
      { bossname: 'Königliches Erdbeergelee', level: 60 },
      { bossname: 'Königliches Zitronengelee', level: 60 },
      { bossname: 'Königliches Blaubeergelee', level: 60 },
    ],
  },
  { dungeonname: 'Brumen Tinctorias Laboratorium', bossname: 'Nelwynn', level: 70 },
  { dungeonname: 'Bilge von Otomais Arche', bossname: 'Gurrlo, der Fürchterliche', level: 70 },
  { dungeonname: 'Krachler Dungeon', bossname: 'Legendärer Mega Krachler', level: 70 },
  { dungeonname: 'Wa Wabbit Bau', bossname: 'Wa Wobot', level: 80 },
  { dungeonname: 'Astaknyden Dungeon', bossname: 'Ur-Astaknyde', level: 90 },
  { dungeonname: 'Dickschädel Staudamm', bossname: 'Oberstnimb Selim Quarz', level: 90 },
  { dungeonname: 'Unterschlupf des Schweinedrachens', bossname: 'Schweinedrachen', level: 100 },
  { dungeonname: 'Höhle des Kuhlosses', bossname: 'Kuhloss', level: 100 },
  { dungeonname: 'Dungeon von Moon', bossname: 'Moon', level: 100 },
  { dungeonname: 'Canidae Dungeon', bossname: 'MuWulf', level: 100 },
  // Stufe 101 - 150
  { dungeonname: 'Shilf Engpass', bossname: 'Groß-Shilf', level: 110 },
  { dungeonname: 'Meister Rabs Bibliothek', bossname: 'Meister Rab', level: 110 },
  { dungeonname: 'Rattendungeon von Bonta', bossname: 'Weiße Ratte', level: 110 },
  { dungeonname: 'Rattendungeon von Brakmar', bossname: 'Schwarze Ratte', level: 110 },
  { dungeonname: 'Unterschlupf des Königlichen Multiblobs', bossname: 'Königlicher Multiblob', level: 120 },
  { dungeonname: 'Herz des Labyrinths des Minotorors', bossname: 'Minotoror', level: 120 },
  { dungeonname: 'Gewächshaus des Königlichen Fressmuts', bossname: 'Königliches Fressmut', level: 120 },
  { dungeonname: 'Königlicher Tofustall', bossname: 'Königlicher Tofu', level: 120 },
  { dungeonname: 'Drachei Dungeon', bossname: 'Crocabulia', level: 120 },
  { dungeonname: 'Unterschlupf des Skeunks', bossname: 'Skeunk', level: 120 },
  { dungeonname: 'Erzfelser Heiligtum', bossname: 'Krakillian Wächter', level: 130 },
  { dungeonname: 'Kanigroulas Unterschlupf', bossname: 'Kanigroula', level: 140 },
  { dungeonname: 'Weich Eich Dungeon', bossname: 'Weich Eich', level: 140 },
  { dungeonname: 'Tynril Dungeon',
    bosses: [
      { bossname: 'Bestürzter Tynril', level: 140 },
      { bossname: 'Perfider Tynril', level: 140 },
      { bossname: 'Verblüffter Tynril', level: 140 },
      { bossname: 'Verdutzter Tynril', level: 140 },
    ],
  },
  { dungeonname: 'King Ping Grotte', bossname: 'King Ping', level: 140 },
  { dungeonname: 'Grabhügel des langen Schlafs', bossname: 'Hell Mina', level: 140 },
  { dungeonname: 'Wrack der Black Rogg', bossname: 'Ben der Ripat', level: 150 },
  { dungeonname: 'Rattendungeon des Schlosses von Amakna', bossname: 'Sphincter Cell', level: 150 },
  // Stufe 151 - 190
  { dungeonname: 'Kimbo Blätterdach', bossname: 'Kimbo', level: 160 },
  { dungeonname: 'Minotot Raum', bossname: 'Minotot', level: 160 },
  { dungeonname: 'Grabgewölbe des Obsidianter', bossname: 'Obsidianter', level: 160 },
  { dungeonname: 'Überflutete Kapelle', bossname: 'Zombrutalist', level: 160 },
  { dungeonname: 'Eisfux Höhlen',
    bosses: [
      { bossname: 'Tengu Eisfux', level: 170 },
      { bossname: 'Fuji Eisfux', level: 190 },
    ],
  },
  { dungeonname: 'Tal der Herrin über die Gewässer', bossname: 'Nagate', level: 170 },
  { dungeonname: 'Pyramide von König Skai', bossname: 'König Skai', level: 170 },
  { dungeonname: 'Unterschlupf des Korrianders', bossname: 'Korriander', level: 180 },
  { dungeonname: 'Höhle des Riesenkrakamors', bossname: 'Riesenkrakamor', level: 180 },
  { dungeonname: 'Bworker Dungeon', bossname: 'Bworker', level: 180 },
  { dungeonname: 'Pilz Dungeon', bossname: 'Stinkeling', level: 180 },
  { dungeonname: 'Tanukouï Sans Werkstatt', bossname: 'Tanukouï San', level: 180 },
  { dungeonname: 'Höhlen des Daxolossus', bossname: 'Daxolossus', level: 190 },
  { dungeonname: 'Feuerwirrk-Fabrik', bossname: 'Fuxoroshi', level: 190 },
  { dungeonname: 'Mine von Arkal', bossname: 'Grollum', level: 190 },
  { dungeonname: 'Vorraum des Barbärenstockes', bossname: 'Himmlischer Barbär', level: 190 },
  { dungeonname: 'Dojo des Windes',
    bosses: [
      { bossname: 'Shihan', level: 190 },
      { bossname: 'Hanshi', level: 190 },
    ],
  },
  // Stufe 191 - 200
  { dungeonname: 'Missiz Frizz Kaltschmiede', bossname: 'Missiz Frizz', level: 190 },
  { dungeonname: 'Sylarghs Transport', bossname: 'Sylargh', level: 190 },
  { dungeonname: 'Die privaten Gesellschaftszimmer R.Klimms', bossname: 'R.Klimm', level: 190 },
  { dungeonname: 'Nilezas Laboratorium', bossname: 'Nileza', level: 190 },
  { dungeonname: 'Graf Primzahls Dungeon', bossname: 'Graf Primzahl', level: 190 },
  { dungeonname: 'Damadryas Bambushain', bossname: 'Damadrya', level: 190 },
  { dungeonname: 'Heiligtum der verirrten Seelen', bossname: 'Katamashii', level: 190 },
];

const DUNGEON_KATEGORIEN = {
  'Level 1-50'    : d => d.level >= 1   && d.level <= 50,
  'Level 51-100'  : d => d.level >= 51  && d.level <= 100,
  'Level 101-150' : d => d.level >= 101 && d.level <= 150,
  'Level 151-190' : d => d.level >= 151 && d.level <= 190,
  'Level 191-200' : d => d.level >= 191 && d.level <= 200,
};

module.exports = { DUNGEON_LISTE, DUNGEON_KATEGORIEN };