const HELP_COMMANDS = [
  // User
  {
    name: 'registrieren',
    description: 'Meldet dich für das Turnier an.',
    descriptionLocalized: {
      de: 'Meldet dich für das Turnier an.',
      en: 'Registers you for the tournament.',
      fr: 'Inscrit ton compte au tournoi.',
      es: 'Te registra en el torneo.',
      it: 'Ti registra al torneo.',
      pt: 'Registra você no torneio.',
    },
    admin: false,
  },
  {
    name: 'arena',
    description: 'Zufällige Arena-Auswahl.',
    descriptionLocalized: {
      de: 'Zufällige Arena-Auswahl.',
      en: 'Picks a random arena.',
      fr: 'Sélectionne une arène aléatoire.',
      es: 'Elige una arena aleatoria.',
      it: 'Seleziona un’arena casuale.',
      pt: 'Seleciona uma arena aleatória.',
    },
    admin: false,
  },
  {
    name: 'achievements',
    description: 'Listet alle Erfolge mit Beschreibung auf.',
    descriptionLocalized: {
      de: 'Listet alle Erfolge mit Beschreibung auf.',
      en: 'Lists all achievements with their descriptions.',
      fr: 'Répertorie tous les succès avec leur description.',
      es: 'Enumera todos los logros con su descripción.',
      it: 'Elenca tutti gli obiettivi con descrizione.',
      pt: 'Lista todas as conquistas com descrição.',
    },
    admin: false,
  },
  {
    name: 'boss',
    description: 'Zeigt Infos zu einem Bossmonster.',
    descriptionLocalized: {
      de: 'Zeigt Infos zu einem Bossmonster.',
      en: 'Shows information about a boss monster.',
      fr: 'Affiche les informations d’un boss.',
      es: 'Muestra información de un jefe.',
      it: 'Mostra le informazioni di un boss.',
      pt: 'Mostra informações sobre um chefe.',
    },
    admin: false,
  },
  {
    name: 'challenges',
    description: 'Listet alle Herausforderungen mit Beschreibung auf.',
    descriptionLocalized: {
      de: 'Listet alle Herausforderungen mit Beschreibung auf.',
      en: 'Lists all challenges with their descriptions.',
      fr: 'Répertorie tous les défis avec leur description.',
      es: 'Enumera todos los desafíos con su descripción.',
      it: 'Elenca tutte le sfide con descrizione.',
      pt: 'Lista todos os desafios com descrição.',
    },
    admin: false,
  },
  {
    name: 'dungeon',
    description: 'Zeigt Infos zu einem Dungeon.',
    descriptionLocalized: {
      de: 'Zeigt Infos zu einem Dungeon.',
      en: 'Shows information about a dungeon.',
      fr: 'Affiche les informations d’un donjon.',
      es: 'Muestra información de un calabozo.',
      it: 'Mostra le informazioni di un dungeon.',
      pt: 'Mostra informações sobre um calabouço.',
    },
    admin: false,
  },
  {
    name: 'bracket',
    description: 'Zeigt Gruppen, Kämpfe und Übersicht der aktuellen Phase an',
    descriptionLocalized: {
      de: 'Zeigt Gruppen, Kämpfe und Übersicht der aktuellen Phase an.',
      en: 'Displays groups, matches and the current phase overview.',
      fr: 'Affiche les groupes, les combats et la phase actuelle.',
      es: 'Muestra los grupos, combates y la fase actual.',
      it: 'Mostra gruppi, incontri e panoramica della fase attuale.',
      pt: 'Mostra grupos, lutas e a fase atual.',
    },
    admin: false,
  },
  {
    name: 'hall_of_fame',
    description: 'Zeigt vergangene Turniere (Podium).',
    descriptionLocalized: {
      de: 'Zeigt vergangene Turniere (Podium).',
      en: 'Shows past tournaments (podium).',
      fr: 'Affiche les anciens tournois (podium).',
      es: 'Muestra torneos anteriores (podio).',
      it: 'Mostra i tornei passati (podio).',
      pt: 'Mostra torneios anteriores (pódio).',
    },
    admin: false,
  },
  {
    name: 'regeln',
    description: 'Zeigt die Turnierregeln.',
    descriptionLocalized: {
      de: 'Zeigt die Turnierregeln.',
      en: 'Displays the tournament rules.',
      fr: 'Affiche les règles du tournoi.',
      es: 'Muestra las reglas del torneo.',
      it: 'Mostra le regole del torneo.',
      pt: 'Mostra as regras do torneio.',
    },
    admin: false,
  },
  {
    name: 'pvp_info',
    description: 'Komplette Turnier-Übersicht (Pott & Status).',
    descriptionLocalized: {
      de: 'Komplette Turnier-Übersicht (Pott & Status).',
      en: 'Complete tournament overview (prize pool & status).',
      fr: 'Vue d’ensemble du tournoi (cagnotte & statut).',
      es: 'Resumen completo del torneo (bote y estado).',
      it: 'Panoramica completa del torneo (montepremi e stato).',
      pt: 'Visão geral completa do torneio (prêmio e status).',
    },
    admin: false,
  },

  // Admin
  {
    name: 'ergebnis_setzen',
    description: 'Admin: Ergebnis eines Kampfes setzen/korrigieren.',
    descriptionLocalized: {
      de: 'Admin: Ergebnis eines Kampfes setzen/korrigieren.',
      en: 'Admin: Set or correct a match result.',
      fr: 'Admin : Définir ou corriger le résultat d’un combat.',
      es: 'Admin: Establece o corrige el resultado de un combate.',
      it: 'Admin: Imposta o corregge il risultato di un incontro.',
      pt: 'Admin: Define ou corrige o resultado de uma luta.',
    },
    admin: true,
  },
  {
    name: 'ergebnisse_wuerfeln',
    description: 'Admin: Zufalls-Ergebnisse für die aktuelle Phase setzen. (Zum Testen)',
    descriptionLocalized: {
      de: 'Admin: Zufalls-Ergebnisse für die aktuelle Phase setzen. (Zum Testen)',
      en: 'Admin: Fill the current phase with random results (testing).',
      fr: 'Admin : Génère des résultats aléatoires pour la phase actuelle (tests).',
      es: 'Admin: Genera resultados aleatorios para la fase actual (pruebas).',
      it: 'Admin: Genera risultati casuali per la fase attuale (test).',
      pt: 'Admin: Gera resultados aleatórios para a fase atual (teste).',
    },
    admin: true,
  },
  {
    name: 'fake_anmeldungen',
    description: 'Admin: Fügt N fiktive Teilnehmer (zum Testen) hinzu.',
    descriptionLocalized: {
      de: 'Admin: Fügt N fiktive Teilnehmer (zum Testen) hinzu.',
      en: 'Admin: Adds N fake participants (testing).',
      fr: 'Admin : Ajoute N participants fictifs (tests).',
      es: 'Admin: Añade N participantes ficticios (pruebas).',
      it: 'Admin: Aggiunge N partecipanti fittizi (test).',
      pt: 'Admin: Adiciona N participantes fictícios (teste).',
    },
    admin: true,
  },
  {
    name: 'language',
    description: 'Admin: Bot-Sprache für diesen Server einstellen.',
    descriptionLocalized: {
      de: 'Admin: Bot-Sprache für diesen Server einstellen.',
      en: 'Admin: Set the bot language for this server.',
      fr: 'Admin : Définit la langue du bot pour ce serveur.',
      es: 'Admin: Configura el idioma del bot en este servidor.',
      it: 'Admin: Imposta la lingua del bot per questo server.',
      pt: 'Admin: Define o idioma do bot para este servidor.',
    },
    admin: true,
  },
  {
    name: 'hof_loeschen',
    description: 'Admin: Löscht einen Hall-of-Fame-Eintrag per Turniernummer. (Zum Testen)',
    descriptionLocalized: {
      de: 'Admin: Löscht einen Hall-of-Fame-Eintrag per Turniernummer. (Zum Testen)',
      en: 'Admin: Deletes a hall-of-fame entry by tournament number (testing).',
      fr: 'Admin : Supprime une entrée du panthéon par numéro de tournoi (tests).',
      es: 'Admin: Elimina una entrada del salón de la fama por número de torneo (pruebas).',
      it: 'Admin: Elimina una voce della hall of fame tramite numero del torneo (test).',
      pt: 'Admin: Remove uma entrada do hall da fama pelo número do torneio (teste).',
    },
    admin: true,
  },
  {
    name: 'pott_setzen',
    description: 'Admin: Pott & Aufteilung (Top 3) setzen.',
    descriptionLocalized: {
      de: 'Admin: Pott & Aufteilung (Top 3) setzen.',
      en: 'Admin: Set prize pool & payout for the top 3.',
      fr: 'Admin : Définit la cagnotte et la répartition du top 3.',
      es: 'Admin: Define el bote y el reparto del top 3.',
      it: 'Admin: Imposta il montepremi e la ripartizione della top 3.',
      pt: 'Admin: Define o prêmio e a divisão do top 3.',
    },
    admin: true,
  },
  {
    name: 'teilnehmer_ersetzen',
    description: 'Admin: Teilnehmer (ID/Name) auf anderen User umstellen und/oder Klasse/Name ändern.',
    descriptionLocalized: {
      de: 'Admin: Teilnehmer (ID/Name) auf anderen User umstellen und/oder Klasse/Name ändern.',
      en: 'Admin: Reassign a participant (ID/name) and optionally update class/name.',
      fr: 'Admin : Réassigne un participant (ID/nom) et met à jour classe/nom.',
      es: 'Admin: Reasigna un participante (ID/nombre) y actualiza clase/nombre.',
      it: 'Admin: Riassegna un partecipante (ID/nome) e aggiorna classe/nome.',
      pt: 'Admin: Reatribui um participante (ID/nome) e atualiza classe/nome.',
    },
    admin: true,
  },
  {
    name: 'pvp_next',
    description: 'Admin: Nächste Phase (Quali → Gruppen → KO → Finale) auslösen.',
    descriptionLocalized: {
      de: 'Admin: Nächste Phase (Quali → Gruppen → KO → Finale) auslösen.',
      en: 'Admin: Advance to the next phase (qualifiers → groups → KO → final).',
      fr: 'Admin : Passe à la prochaine phase (qualifs → groupes → élimination → finale).',
      es: 'Admin: Avanza a la siguiente fase (clasificatoria → grupos → KO → final).',
      it: 'Admin: Avanza alla fase successiva (qualifiche → gironi → KO → finale).',
      pt: 'Admin: Avança para a próxima fase (classificatória → grupos → mata-mata → final).',
    },
    admin: true,
  },
  {
    name: 'pvp_start',
    description: 'Admin: Startet ein Turnier (Modus auswählen).',
    descriptionLocalized: {
      de: 'Admin: Startet ein Turnier (Modus auswählen).',
      en: 'Admin: Starts a tournament (choose the mode).',
      fr: 'Admin : Lance un tournoi (choisir le mode).',
      es: 'Admin: Inicia un torneo (elige el modo).',
      it: 'Admin: Avvia un torneo (scegli la modalità).',
      pt: 'Admin: Inicia um torneio (escolha o modo).',
    },
    admin: true,
  },
  {
    name: 'pvp_stop',
    description: 'Admin: Beendet das Turnier & leert Daten.',
    descriptionLocalized: {
      de: 'Admin: Beendet das Turnier & leert Daten.',
      en: 'Admin: Stops the tournament and clears all data.',
      fr: 'Admin : Arrête le tournoi et vide les données.',
      es: 'Admin: Detiene el torneo y borra los datos.',
      it: 'Admin: Ferma il torneo e cancella i dati.',
      pt: 'Admin: Encerra o torneio e limpa os dados.',
    },
    admin: true,
  },
];

module.exports = { HELP_COMMANDS };