/**
 * @typedef {Object} SpellDefinition
 * @property {string} id Eindeutiger Spell-Slug, kombiniert aus Klassen-ID und Spell-Namen.
 * @property {string} name Anzeigetext des Spells.
 * @property {string} description Kurzbeschreibung des Effekts.
 * @property {string} emoji Discord-Emoji Kennung (resolveDiscordEmoji).
 * @property {string} icon Vollständige Icon-URL (ICON_BASE/spell_icons/<class>/<spell>.png).
 * @property {string} element Primäres Element (z.B. earth, fire, water, air, neutral).
 * @property {{min:number,max:number}} baseDamage Grundschaden ohne Krit.
 * @property {{min:number,max:number}} [criticalDamage] Kritischer Schaden.
 * @property {number} apCost AP-Kosten pro Zauber.
 * @property {string} type Primärer Spell-Typ (damage, heal, summon, support etc.).
 * @property {Object} [scalingStats] Skalierungsdefinitionen (z.B. { primary: 'strength', includesPower: true }).
 * @property {Object} [secondaryEffects] Flags/Parameter für Sekundäreffekte (z.B. Zustände, Steals, Pushs).
 * @property {string} [calculationVariant] Referenz auf besondere Berechnungslogik.
 * @property {Object} [range] Reichweitenparameter (min, max, modifiable, requiresLineOfSight, linear etc.).
 * @property {Object} [parameters] Zusätzliche Parameter für die Schadens-/Effektberechnung.
 */

const { ICON_BASE, resolveDiscordEmoji } = require('./shared');
const { KLASSE_LISTE } = require('./classes');

const SPELLS_BY_CLASS = {
  cra: [
    {
      id: 'cra_magic-arrow',
      name: 'Magischer Pfeil',
      description: 'Feuert einen präzisen Luftpfeil mit Chance auf AP-Reduktion.',
      emoji: resolveDiscordEmoji('spell_magic_arrow', '🏹'),
      icon: `${ICON_BASE}/spell_icons/cra/magic_arrow.png`,
      element: 'air',
      baseDamage: { min: 12, max: 16 },
      criticalDamage: { min: 15, max: 20 },
      apCost: 3,
      type: 'damage',
      range: { min: 7, max: 9, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'agility', includesPower: true },
      calculationVariant: 'projectile',
      secondaryEffects: {
        apReduction: { chance: 0.1, amount: 1 },
      },
      parameters: { zone: 'single', maxCastPerTurn: 3, damageRatio: 1 },
    },
    {
      id: 'cra_stormfire',
      name: 'Sturmfeuer',
      description: 'Beschießt ein Gebiet mit feurigen Pfeilen und stößt Gegner zurück.',
      emoji: resolveDiscordEmoji('spell_stormfire', '🌪️'),
      icon: `${ICON_BASE}/spell_icons/cra/stormfire.png`,
      element: 'fire',
      baseDamage: { min: 18, max: 24 },
      criticalDamage: { min: 22, max: 28 },
      apCost: 4,
      type: 'damage',
      range: { min: 4, max: 6, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'intelligence', includesPower: true },
      calculationVariant: 'aoe',
      secondaryEffects: {
        pushback: { cells: 1 },
      },
      parameters: { zone: 'circle', radius: 2, maxCastPerTurn: 2 },
    },
  ],
  ecaflip: [
    {
      id: 'ecaflip_lucky-claw',
      name: 'Glückskralle',
      description: 'Schadet dem Ziel und kann Lebenspunkte stehlen, wenn ein Krit ausgelöst wird.',
      emoji: resolveDiscordEmoji('spell_lucky_claw', '🐾'),
      icon: `${ICON_BASE}/spell_icons/ecaflip/lucky_claw.png`,
      element: 'earth',
      baseDamage: { min: 14, max: 19 },
      criticalDamage: { min: 18, max: 24 },
      apCost: 3,
      type: 'damage',
      range: { min: 1, max: 4, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'strength', includesPower: true },
      calculationVariant: 'lifesteal',
      secondaryEffects: {
        lifeSteal: { ratio: 0.2 },
        luckBonus: { chance: 0.25, damageMultiplier: 1.25 },
      },
      parameters: { zone: 'single', critBonus: 0.15 },
    },
    {
      id: 'ecaflip_tarot-throw',
      name: 'Kartentrick',
      description: 'Wirft eine Tarotkarte, die zufällige Buffs oder Debuffs auslösen kann.',
      emoji: resolveDiscordEmoji('spell_tarot_throw', '🃏'),
      icon: `${ICON_BASE}/spell_icons/ecaflip/tarot_throw.png`,
      element: 'neutral',
      baseDamage: { min: 10, max: 15 },
      apCost: 2,
      type: 'support',
      range: { min: 1, max: 6, modifiable: true, requiresLineOfSight: false },
      scalingStats: { primary: 'chance', includesPower: false },
      calculationVariant: 'randomized',
      secondaryEffects: {
        randomBuff: { duration: 2, effectsPool: ['damage', 'heal', 'lock'] },
      },
      parameters: { zone: 'single', maxCastPerTarget: 1 },
    },
  ],
  eniripsa: [
    {
      id: 'eniripsa_regeneration-word',
      name: 'Regenerationswort',
      description: 'Heilt Verbündete über mehrere Runden.',
      emoji: resolveDiscordEmoji('spell_regeneration_word', '💖'),
      icon: `${ICON_BASE}/spell_icons/eniripsa/regeneration_word.png`,
      element: 'water',
      baseDamage: { min: -18, max: -24 },
      criticalDamage: { min: -22, max: -28 },
      apCost: 3,
      type: 'heal',
      range: { min: 1, max: 7, modifiable: true, requiresLineOfSight: false },
      scalingStats: { primary: 'intelligence', includesPower: true },
      calculationVariant: 'heal-over-time',
      secondaryEffects: {
        regen: { duration: 3, perTurn: 8 },
      },
      parameters: { zone: 'single', healRatio: 1, maxStack: 1 },
    },
    {
      id: 'eniripsa_revitalizing-word',
      name: 'Revitalisierungswort',
      description: 'Starker Burst-Heal mit Chance auf Entfernen negativer Effekte.',
      emoji: resolveDiscordEmoji('spell_revitalizing_word', '✨'),
      icon: `${ICON_BASE}/spell_icons/eniripsa/revitalizing_word.png`,
      element: 'water',
      baseDamage: { min: -28, max: -36 },
      criticalDamage: { min: -32, max: -42 },
      apCost: 4,
      type: 'heal',
      range: { min: 1, max: 6, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'intelligence', includesPower: true },
      calculationVariant: 'burst-heal',
      secondaryEffects: {
        dispel: { chance: 0.3, removes: ['poison', 'mpReduction'] },
      },
      parameters: { zone: 'single', maxCastPerTurn: 2 },
    },
  ],
  enutrof: [
    {
      id: 'enutrof_coin-toss',
      name: 'Münzschleuder',
      description: 'Wirft schwere Münzen und kann Schatzmarkierungen auslösen.',
      emoji: resolveDiscordEmoji('spell_coin_toss', '🪙'),
      icon: `${ICON_BASE}/spell_icons/enutrof/coin_toss.png`,
      element: 'water',
      baseDamage: { min: 16, max: 22 },
      criticalDamage: { min: 20, max: 26 },
      apCost: 3,
      type: 'damage',
      range: { min: 3, max: 8, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'chance', includesPower: true },
      calculationVariant: 'projectile',
      secondaryEffects: {
        prospectingMark: { chance: 0.25, bonusLoot: true },
      },
      parameters: { zone: 'single', damageRatio: 1.05 },
    },
    {
      id: 'enutrof_riches-scent',
      name: 'Schatzgeruch',
      description: 'Markiert ein Ziel und erhöht Chance- sowie Drop-Boni.',
      emoji: resolveDiscordEmoji('spell_riches_scent', '👃'),
      icon: `${ICON_BASE}/spell_icons/enutrof/riches_scent.png`,
      element: 'earth',
      baseDamage: { min: 0, max: 0 },
      apCost: 2,
      type: 'support',
      range: { min: 1, max: 6, modifiable: true, requiresLineOfSight: false },
      scalingStats: { primary: 'prospection', includesPower: false },
      calculationVariant: 'mark',
      secondaryEffects: {
        lootMark: { duration: 3, dropBonus: 0.1 },
      },
      parameters: { zone: 'single', maxCastPerTarget: 1 },
    },
  ],
  feca: [
    {
      id: 'feca_flame-glyph',
      name: 'Glyph der Flammen',
      description: 'Platziert eine Glyph, die Feuerschaden verursacht.',
      emoji: resolveDiscordEmoji('spell_flame_glyph', '🔥'),
      icon: `${ICON_BASE}/spell_icons/feca/flame_glyph.png`,
      element: 'fire',
      baseDamage: { min: 9, max: 12 },
      criticalDamage: { min: 11, max: 15 },
      apCost: 3,
      type: 'damage',
      range: { min: 1, max: 5, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'intelligence', includesPower: true },
      calculationVariant: 'glyph',
      secondaryEffects: {
        zonePersistency: { duration: 2, zone: 'cross', size: 1 },
      },
      parameters: { zone: 'glyph', radius: 1, tickDamage: true },
    },
    {
      id: 'feca_fortified-shield',
      name: 'Verstärkter Schild',
      description: 'Erhöht die Widerstände und gewährt einen Block-Schirm.',
      emoji: resolveDiscordEmoji('spell_fortified_shield', '🛡️'),
      icon: `${ICON_BASE}/spell_icons/feca/fortified_shield.png`,
      element: 'neutral',
      baseDamage: { min: 0, max: 0 },
      apCost: 2,
      type: 'support',
      range: { min: 1, max: 1, modifiable: false, requiresLineOfSight: true },
      scalingStats: { primary: 'strength', includesPower: false },
      calculationVariant: 'shield',
      secondaryEffects: {
        shield: { valueRatio: 0.2, duration: 2 },
        resistBonus: { percent: 0.1 },
      },
      parameters: { zone: 'single', maxCastPerTarget: 1 },
    },
  ],
  rogue: [
    {
      id: 'rogue_quick-bomb',
      name: 'Schnellzünderbombe',
      description: 'Platziert eine Bombe, die nach einer Runde explodiert.',
      emoji: resolveDiscordEmoji('spell_quick_bomb', '💣'),
      icon: `${ICON_BASE}/spell_icons/rogue/quick_bomb.png`,
      element: 'fire',
      baseDamage: { min: 20, max: 28 },
      criticalDamage: { min: 24, max: 32 },
      apCost: 3,
      type: 'damage',
      range: { min: 1, max: 6, modifiable: true, requiresLineOfSight: false },
      scalingStats: { primary: 'intelligence', includesPower: true },
      calculationVariant: 'bomb',
      secondaryEffects: {
        delayedExplosion: { delay: 1, zone: 'circle', radius: 2 },
      },
      parameters: { zone: 'bomb', comboMultiplier: 0.2 },
    },
    {
      id: 'rogue_pulsar',
      name: 'Pulverisierung',
      description: 'Verbraucht verbleibende AP für massiven Schaden.',
      emoji: resolveDiscordEmoji('spell_pulsar', '💥'),
      icon: `${ICON_BASE}/spell_icons/rogue/pulsar.png`,
      element: 'air',
      baseDamage: { min: 8, max: 10 },
      criticalDamage: { min: 12, max: 14 },
      apCost: 2,
      type: 'damage',
      range: { min: 1, max: 5, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'agility', includesPower: true },
      calculationVariant: 'ap-burn',
      secondaryEffects: {
        apConversion: { ratio: 1.4, consumesRemainingAp: true },
      },
      parameters: { zone: 'single', minApConsumed: 2 },
    },
  ],
  iop: [
    {
      id: 'iop_sword-blow',
      name: 'Schwertstoß',
      description: 'Schneller Nahkampfangriff mit neutralem Schaden.',
      emoji: resolveDiscordEmoji('spell_sword_blow', '⚔️'),
      icon: `${ICON_BASE}/spell_icons/iop/sword_blow.png`,
      element: 'neutral',
      baseDamage: { min: 18, max: 24 },
      criticalDamage: { min: 22, max: 30 },
      apCost: 3,
      type: 'damage',
      range: { min: 1, max: 1, modifiable: false, requiresLineOfSight: true },
      scalingStats: { primary: 'strength', includesPower: true },
      calculationVariant: 'melee',
      secondaryEffects: {
        combo: { bonusPerHit: 0.05, duration: 2 },
      },
      parameters: { zone: 'single', linearOnly: true },
    },
    {
      id: 'iop_wrath',
      name: 'Zorn des Iop',
      description: 'Lädt mehrere Runden auf und verursacht gewaltigen Schaden.',
      emoji: resolveDiscordEmoji('spell_wrath', '🌋'),
      icon: `${ICON_BASE}/spell_icons/iop/wrath.png`,
      element: 'fire',
      baseDamage: { min: 45, max: 52 },
      criticalDamage: { min: 52, max: 60 },
      apCost: 6,
      type: 'damage',
      range: { min: 1, max: 1, modifiable: false, requiresLineOfSight: true },
      scalingStats: { primary: 'strength', includesPower: true },
      calculationVariant: 'charged-hit',
      secondaryEffects: {
        charge: { turns: 2, damageMultiplier: 1.8 },
      },
      parameters: { zone: 'single', cooldown: 5 },
    },
  ],
  masqueraider: [
    {
      id: 'masqueraider_psycho-mask',
      name: 'Psycho-Maske',
      description: 'Wechselt die Maske und erhöht Schaden auf Kosten der Resistenz.',
      emoji: resolveDiscordEmoji('spell_psycho_mask', '🎭'),
      icon: `${ICON_BASE}/spell_icons/masqueraider/psycho_mask.png`,
      element: 'neutral',
      baseDamage: { min: 0, max: 0 },
      apCost: 2,
      type: 'support',
      range: { min: 0, max: 0, modifiable: false, requiresLineOfSight: false },
      scalingStats: { primary: 'strength', includesPower: false },
      calculationVariant: 'stance',
      secondaryEffects: {
        stance: { mask: 'psycho', damageBonus: 0.25, resistPenalty: 0.1 },
      },
      parameters: { zone: 'self', duration: 3 },
    },
    {
      id: 'masqueraider_whip-kick',
      name: 'Wirbelnder Tritt',
      description: 'Rotierender Angriff, der Gegner schiebt und Schaden verteilt.',
      emoji: resolveDiscordEmoji('spell_whip_kick', '🌀'),
      icon: `${ICON_BASE}/spell_icons/masqueraider/whip_kick.png`,
      element: 'air',
      baseDamage: { min: 20, max: 26 },
      criticalDamage: { min: 24, max: 30 },
      apCost: 4,
      type: 'damage',
      range: { min: 1, max: 2, modifiable: false, requiresLineOfSight: false },
      scalingStats: { primary: 'agility', includesPower: true },
      calculationVariant: 'melee-aoe',
      secondaryEffects: {
        pushback: { cells: 1, zone: 'circle' },
      },
      parameters: { zone: 'circle', radius: 1 },
    },
  ],
  osamodas: [
    {
      id: 'osamodas_summon-tofu',
      name: 'Beschwörung: Tofu',
      description: 'Beschwört einen beweglichen Tofu, der Luftschaden verursacht.',
      emoji: resolveDiscordEmoji('spell_summon_tofu', '🐤'),
      icon: `${ICON_BASE}/spell_icons/osamodas/summon_tofu.png`,
      element: 'air',
      baseDamage: { min: 8, max: 12 },
      apCost: 3,
      type: 'summon',
      range: { min: 1, max: 6, modifiable: true, requiresLineOfSight: false },
      scalingStats: { primary: 'summons', includesPower: false },
      calculationVariant: 'summon',
      secondaryEffects: {
        summon: { creature: 'tofu', duration: 3, ai: 'aggressive' },
      },
      parameters: { zone: 'single', maxSummons: 1 },
    },
    {
      id: 'osamodas_animal-synergy',
      name: 'Tiergefährte',
      description: 'Stärkt beschworene Kreaturen mit zusätzlichem Schaden.',
      emoji: resolveDiscordEmoji('spell_animal_synergy', '🐾'),
      icon: `${ICON_BASE}/spell_icons/osamodas/animal_synergy.png`,
      element: 'earth',
      baseDamage: { min: 0, max: 0 },
      apCost: 2,
      type: 'support',
      range: { min: 1, max: 7, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'strength', includesPower: false },
      calculationVariant: 'buff',
      secondaryEffects: {
        summonBuff: { damageBonus: 0.2, duration: 2 },
      },
      parameters: { zone: 'single', affectsSummonsOnly: true },
    },
  ],
  pandawa: [
    {
      id: 'pandawa_explosive-flask',
      name: 'Explosive Flasche',
      description: 'Wirft eine explosive Flasche mit Flächenschaden.',
      emoji: resolveDiscordEmoji('spell_explosive_flask', '🍶'),
      icon: `${ICON_BASE}/spell_icons/pandawa/explosive_flask.png`,
      element: 'fire',
      baseDamage: { min: 22, max: 28 },
      criticalDamage: { min: 26, max: 32 },
      apCost: 4,
      type: 'damage',
      range: { min: 2, max: 7, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'intelligence', includesPower: true },
      calculationVariant: 'throwable-aoe',
      secondaryEffects: {
        drunkState: { applies: true, duration: 1 },
      },
      parameters: { zone: 'circle', radius: 1 },
    },
    {
      id: 'pandawa_bamboo-milk',
      name: 'Bambusmilch',
      description: 'Heilt Verbündete und entfernt den Betrunkenen Zustand.',
      emoji: resolveDiscordEmoji('spell_bamboo_milk', '🥛'),
      icon: `${ICON_BASE}/spell_icons/pandawa/bamboo_milk.png`,
      element: 'water',
      baseDamage: { min: -16, max: -22 },
      criticalDamage: { min: -20, max: -26 },
      apCost: 3,
      type: 'heal',
      range: { min: 1, max: 4, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'chance', includesPower: true },
      calculationVariant: 'cleanse-heal',
      secondaryEffects: {
        cleanse: { removesState: 'drunk' },
      },
      parameters: { zone: 'single', cooldown: 1 },
    },
  ],
  sacrieur: [
    {
      id: 'sacrieur_bloodthirsty-madness',
      name: 'Blutbad',
      description: 'Opfert Lebenspunkte für erhöhten Schaden in Folgezügen.',
      emoji: resolveDiscordEmoji('spell_bloodthirsty_madness', '🩸'),
      icon: `${ICON_BASE}/spell_icons/sacrieur/bloodthirsty_madness.png`,
      element: 'fire',
      baseDamage: { min: 24, max: 30 },
      criticalDamage: { min: 28, max: 34 },
      apCost: 4,
      type: 'damage',
      range: { min: 1, max: 1, modifiable: false, requiresLineOfSight: true },
      scalingStats: { primary: 'intelligence', includesPower: true },
      calculationVariant: 'self-harm',
      secondaryEffects: {
        selfDamage: { percentCurrentHp: 0.1 },
        damageBuff: { percent: 0.2, duration: 2 },
      },
      parameters: { zone: 'single', affectsCaster: true },
    },
    {
      id: 'sacrieur_punishment',
      name: 'Bestrafung',
      description: 'Skaliert Schaden basierend auf fehlenden Lebenspunkten.',
      emoji: resolveDiscordEmoji('spell_punishment', '⚖️'),
      icon: `${ICON_BASE}/spell_icons/sacrieur/punishment.png`,
      element: 'earth',
      baseDamage: { min: 20, max: 26 },
      criticalDamage: { min: 24, max: 32 },
      apCost: 4,
      type: 'damage',
      range: { min: 1, max: 1, modifiable: false, requiresLineOfSight: true },
      scalingStats: { primary: 'strength', includesPower: true },
      calculationVariant: 'missing-hp-scaling',
      secondaryEffects: {
        damageRamp: { ratioPerMissingHp: 0.005 },
      },
      parameters: { zone: 'single', cooldown: 2 },
    },
  ],
  sadida: [
    {
      id: 'sadida_brambly',
      name: 'Erdbrambel',
      description: 'Lässt Dornen wachsen, die Gegner verlangsamen.',
      emoji: resolveDiscordEmoji('spell_brambly', '🌿'),
      icon: `${ICON_BASE}/spell_icons/sadida/brambly.png`,
      element: 'earth',
      baseDamage: { min: 14, max: 20 },
      criticalDamage: { min: 18, max: 24 },
      apCost: 3,
      type: 'damage',
      range: { min: 3, max: 7, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'strength', includesPower: true },
      calculationVariant: 'rooting',
      secondaryEffects: {
        mpReduction: { amount: 2, duration: 1 },
      },
      parameters: { zone: 'line', linearOnly: true },
    },
    {
      id: 'sadida_tree-armor',
      name: 'Baumschutz',
      description: 'Verwandelt einen Verbündeten in einen Baum mit hoher Resistenz.',
      emoji: resolveDiscordEmoji('spell_tree_armor', '🌳'),
      icon: `${ICON_BASE}/spell_icons/sadida/tree_armor.png`,
      element: 'earth',
      baseDamage: { min: 0, max: 0 },
      apCost: 2,
      type: 'support',
      range: { min: 1, max: 6, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'strength', includesPower: false },
      calculationVariant: 'transformation',
      secondaryEffects: {
        transform: { state: 'tree', duration: 2, resistBonus: 0.3 },
      },
      parameters: { zone: 'single', immobilized: true },
    },
  ],
  sram: [
    {
      id: 'sram_ambush',
      name: 'Hinterhalt',
      description: 'Richtet schweren Schaden aus, wenn das Ziel unsichtbar ist.',
      emoji: resolveDiscordEmoji('spell_ambush', '🗡️'),
      icon: `${ICON_BASE}/spell_icons/sram/ambush.png`,
      element: 'earth',
      baseDamage: { min: 22, max: 28 },
      criticalDamage: { min: 26, max: 34 },
      apCost: 4,
      type: 'damage',
      range: { min: 1, max: 3, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'strength', includesPower: true },
      calculationVariant: 'trap-trigger',
      secondaryEffects: {
        backstab: { bonusMultiplier: 1.4, requiresInvisibility: true },
      },
      parameters: { zone: 'single', trapInteraction: true },
    },
    {
      id: 'sram_invisibility',
      name: 'Unsichtbarkeit',
      description: 'Macht den Sram für mehrere Runden unsichtbar.',
      emoji: resolveDiscordEmoji('spell_invisibility', '🫥'),
      icon: `${ICON_BASE}/spell_icons/sram/invisibility.png`,
      element: 'air',
      baseDamage: { min: 0, max: 0 },
      apCost: 2,
      type: 'support',
      range: { min: 0, max: 0, modifiable: false, requiresLineOfSight: false },
      scalingStats: { primary: 'agility', includesPower: false },
      calculationVariant: 'state',
      secondaryEffects: {
        invisibility: { duration: 2, mpBonus: 1 },
      },
      parameters: { zone: 'self', cooldown: 3 },
    },
  ],
  foggernaut: [
    {
      id: 'foggernaut_harpooner',
      name: 'Harponierturm',
      description: 'Stellt einen Harpunenturm auf, der Distanzschaden verursacht.',
      emoji: resolveDiscordEmoji('spell_harpooner', '🎯'),
      icon: `${ICON_BASE}/spell_icons/foggernaut/harpooner.png`,
      element: 'water',
      baseDamage: { min: 14, max: 20 },
      criticalDamage: { min: 18, max: 24 },
      apCost: 3,
      type: 'summon',
      range: { min: 1, max: 5, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'chance', includesPower: true },
      calculationVariant: 'turret',
      secondaryEffects: {
        summon: { creature: 'harpooner', duration: 3, ai: 'ranged' },
      },
      parameters: { zone: 'single', maxSummons: 1 },
    },
    {
      id: 'foggernaut_salvo',
      name: 'Salve',
      description: 'Feuert eine Druckwelle, die Gegner zurückstößt.',
      emoji: resolveDiscordEmoji('spell_salvo', '💨'),
      icon: `${ICON_BASE}/spell_icons/foggernaut/salvo.png`,
      element: 'air',
      baseDamage: { min: 20, max: 26 },
      criticalDamage: { min: 24, max: 30 },
      apCost: 4,
      type: 'damage',
      range: { min: 2, max: 6, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'agility', includesPower: true },
      calculationVariant: 'cone',
      secondaryEffects: {
        pushback: { cells: 2, zone: 'cone' },
      },
      parameters: { zone: 'cone', size: 3 },
    },
  ],
  xelor: [
    {
      id: 'xelor_sandglass',
      name: 'Sanduhr des Xelor',
      description: 'Entzieht AP und verursacht Wasserschaden.',
      emoji: resolveDiscordEmoji('spell_sandglass', '⏳'),
      icon: `${ICON_BASE}/spell_icons/xelor/sandglass.png`,
      element: 'water',
      baseDamage: { min: 12, max: 18 },
      criticalDamage: { min: 15, max: 21 },
      apCost: 3,
      type: 'damage',
      range: { min: 1, max: 7, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'chance', includesPower: true },
      calculationVariant: 'ap-removal',
      secondaryEffects: {
        apReduction: { amount: 2, chance: 0.3 },
      },
      parameters: { zone: 'line', linearOnly: true },
    },
    {
      id: 'xelor_time-theft',
      name: 'Zeitdieb',
      description: 'Stiehlt AP und gewährt sie dem Xelor.',
      emoji: resolveDiscordEmoji('spell_time_theft', '🕰️'),
      icon: `${ICON_BASE}/spell_icons/xelor/time_theft.png`,
      element: 'air',
      baseDamage: { min: 8, max: 12 },
      criticalDamage: { min: 11, max: 15 },
      apCost: 2,
      type: 'steal',
      range: { min: 1, max: 6, modifiable: true, requiresLineOfSight: true },
      scalingStats: { primary: 'agility', includesPower: true },
      calculationVariant: 'ap-steal',
      secondaryEffects: {
        apSteal: { amount: 1, duration: 1 },
      },
      parameters: { zone: 'single', maxCastPerTarget: 2 },
    },
  ],
};

for (const klasse of KLASSE_LISTE) {
  if (!SPELLS_BY_CLASS[klasse.id]) {
    SPELLS_BY_CLASS[klasse.id] = [];
  }
}

const SPELL_LIST = Object.entries(SPELLS_BY_CLASS).flatMap(([klasseId, spells]) =>
  spells.map((spell, index) => ({
    ...spell,
    order: index,
    classId: klasseId,
  })),
);

module.exports = { SPELLS_BY_CLASS, SPELL_LIST };